[unstable]
build-std = ["core", "compiler_builtins"]

[alias]
kernel = [
  "build",
  "-Zbuild-std=core,compiler_builtins",
  "-Zbuild-std-features=mem",
  "--target", "x86_64-blog_os.json"
]

[build]
target = "x86_64-blog_os.json"
